version: "2.2"

services:
  uniops-web:
    container_name: uniops-web
    image: uniops-web
    build: .
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${BASE_DIR}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${BASE_DIR}/dist/:/usr/share/nginx/html/
    ports:
      - 3000:80

networks:
  default:
    external:
      name: uniops-web-network
